"""empty message

Revision ID: 3d05acd3338f
Revises: 1ffe30df6a90
Create Date: 2021-04-18 12:47:14.083935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d05acd3338f'
down_revision = '1ffe30df6a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=True)
    # ### end Alembic commands ###
